name: Synapse
options:
  bundleIdPrefix: com.Synapse
  deploymentTarget:
    macOS: "14.0"
  createIntermediateGroups: true
  xcodeVersion: "16.0"

packages:
  SwiftTerm:
    url: https://github.com/migueldeicaza/SwiftTerm
    from: 1.2.0
  Grape:
    url: https://github.com/SwiftGraphs/Grape
    from: 1.1.0

targets:
  Synapse:
    type: application
    platform: macOS
    sources:
      - Synapse
      - Synapse/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.Synapse.app
        PRODUCT_NAME: Synapse
        SWIFT_VERSION: 5.0
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        INFOPLIST_FILE: Synapse/Info.plist
        ENABLE_HARDENED_RUNTIME: YES
      configs:
        Release:
          CODE_SIGN_STYLE: Manual
          DEVELOPMENT_TEAM: 299R8V27FZ
          CODE_SIGN_IDENTITY: Developer ID Application
    dependencies:
      - package: SwiftTerm
      - package: Grape
    entitlements:
      path: Synapse/Synapse.entitlements
      properties:
        com.apple.security.app-sandbox: false

  SynapseTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - SynapseTests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.Synapse.app.tests
        SWIFT_VERSION: 5.0
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        GENERATE_INFOPLIST_FILE: YES
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Synapse.app/Contents/MacOS/Synapse"
        BUNDLE_LOADER: "$(TEST_HOST)"
    dependencies:
      - target: Synapse
